dist: bionic
language: rust
sudo: false

branches:
  except:
    - /^v[0-9]/

matrix:
  include:
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu

    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu

    - os: osx
      rust: stable
      env: TARGET=x86_64_apple-darwin

script:
  - cargo check
  - cargo test

notifications:
  email: false
